# URL который будем проверять health check
url: https://es-shkola.ru

# временной период (в секундах), через который приложение снова должно проверить HTTP статус указанного URL
retry_after: 3600 # 60 min

# название файла логов куда будет записывать техническая информация о проведенных проверках
log_file: logrus.log